# Generated by Django 3.1.6 on 2021-02-09 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songpath', models.CharField(max_length=50, unique=True)),
                ('songname', models.CharField(max_length=50, unique=True)),
                ('artist', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userplaylists',
            name='playlistowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicapp.song'),
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
