# Generated by Django 3.1.6 on 2021-02-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20210209_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songpath',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
