# Generated by Django 3.1.6 on 2021-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20210209_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
