# Generated by Django 3.1.7 on 2021-03-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20210209_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songlength',
            field=models.CharField(default='04:00', max_length=10),
        ),
    ]
